# Stage 1 - the build process

FROM node:8 as build

WORKDIR /var/news-demo

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2 - the production environment

FROM nginx:1.15-alpine

COPY --from=build /var/news-demo/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
