export const FETCH_NEWS_ITEMS = 'FETCH_NEWS_ITEMS';
export const FETCH_NEWS_ITEMS_SUCCESS = 'FETCH_NEWS_ITEMS_SUCCESS';
export const FETCH_NEWS_ITEMS_FAIL = 'FETCH_NEWS_ITEMS_FAIL';
export const SHOW_NEWS_ITEM = 'SHOW_NEWS_ITEM';
export const CLOSE_NEWS_ITEM = 'CLOSE_NEWS_ITEM';
